# Numpy Tutorial


In [3]:
import numpy as np

## The basics

In [51]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [20]:
#You can also specify the datatype value while creating an array
c = np.array([4,5,6,8],dtype = 'int16')
print(c.dtype)

int16


In [8]:
b = np.array([[9.1,8.2,7.4],[6.7,3.7,2.3]])
print(b)

[[9.1 8.2 7.4]
 [6.7 3.7 2.3]]


In [12]:
#Get dimensions using ndim method
print("Dimension of a is ",a.ndim)
print("Dimension of b is ",b.ndim)

Dimension of a is  1
Dimension of b is  2


In [16]:
#To know the shape of the array (row,column) and when the row is 1, it will output only the column
print(a.shape)
b.shape

(3,)


(2, 3)

In [24]:
# Get the type using variable.dtype method
print(a.dtype)
b.dtype

int32


dtype('float64')

In [107]:
# To know the number of bytes a particular value is taking in memory we can use the itemsize method
print(a.itemsize) #The o/p 4 means that each element in it is taking 4 bytes in memory
print(c.itemsize)#The o/p 2 means that each element in it is taking 2 bytes in memory

4
2
14


In [33]:
#To know the complete size or number of bytes a particular array is occupying can be done using nbytes method
b.nbytes # it is equal to number of bytes each item takes * no of items in array which can also be obtained from a.size method which return the no of items in array

48

.








# Accessing/Changing specific elements,rows,columns etc

In [60]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [61]:
#Get specific element in the form of [Row,Column]
print("particular element from a : ",a[0,2]) #0th row and 2nd column
print("The result can be achieved through negative notation as well", a[0,-5])

#get a specific row
print("To print second row : ",a[1,:] )

#get specific column
print("To print a 4th column :",a[:,3]) #indexing starts from 0



particular element from a :  3
The result can be achieved through negative notation as well 3
To print second row :  [ 8  9 10 11 12 13 14]
To print a 4th column : [ 4 11]


2

In [66]:
#Getting a little more fancy [start_index:end_index:step_size]
a[0,1:-1:2] 

#Here what we did is we extracted all the values from zeroth row and values from first column 
#to sixth column with a step of 2


array([2, 4, 6])

In [70]:
#to change the element from a particular position
a[1,4] = 55
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 55, 13, 14]])

In [75]:
#We can replace value of a particular series as well
a[:,2] = 80
a

a[0,:] = [90,91,92,93,94,95,96]
a

array([[90, 91, 92, 93, 94, 95, 96],
       [ 8,  9, 80, 11, 55, 13, 14]])

### 3D example

In [85]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

# To get specific element

b[:,1,0]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array([3, 7])

In [88]:
#Replace
b[:,1,0] = [8,9]
b

array([[[1, 2],
        [8, 4]],

       [[5, 6],
        [9, 8]]])

## Initializing Different Types of Arrays

In [96]:
# All 0's matrix
np.zeros((3,3)) #--> Put in no of rows and columns

# Can be 3 dimensional as well
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [305]:
# All 1's matrix
g =np.ones((4,2))
print(g)
#in 3 dimension
f = np.ones((4,2,3) ,dtype = 'int16')
f

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [112]:
#To initialize matrix with any other number we use np.full which takes two parameters
np.full((4,4), 88)

array([[88, 88, 88, 88],
       [88, 88, 88, 88],
       [88, 88, 88, 88],
       [88, 88, 88, 88]])

In [114]:
# To initialize an array which is similar to 
# a previously generated array with
# any other number (full_like)
np.full_like(f,5)

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]], dtype=int16)

In [124]:
#Initialize array of random numbers
np.random.rand(4,2)

array([[0.42463553, 0.18833709],
       [0.0524142 , 0.60370255],
       [0.25565472, 0.86422387],
       [0.6816586 , 0.97549144]])

In [170]:
# If you want to pass on shape of previously generated array
#and generate new array with random numbers you
#can use random_sample
g = np.random.random_sample(f.shape)
print(g)

[[[0.44174248 0.76875172 0.02735815]
  [0.60536068 0.79288742 0.39797974]]

 [[0.61036194 0.1237485  0.58724306]
  [0.62228396 0.84425997 0.95725178]]

 [[0.15859751 0.94941046 0.82380073]
  [0.7561711  0.7977626  0.09549792]]

 [[0.06684179 0.32119364 0.9092828 ]
  [0.59592517 0.50761875 0.72162637]]]


In [172]:
# To generate random no array with integer values
h = np.random.randint(1, 99,size=(3,3))
print(h)

[[93  3 18]
 [58  5 31]
 [76 95 30]]


In [175]:
#To generate identity matrix 
#(only takes one argument since identity matrix is always a square matrix)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [181]:
#Repeat an array
arr = np.array([1,2,4])
r1 = np.repeat(arr,4,axis = 0)
r1

array([1, 1, 1, 1, 2, 2, 2, 2, 4, 4, 4, 4])

In [193]:
output = np.ones((5,5))
print('initial input is \n',output,'\n')

z = np.zeros((3,3))

z[1,1] = 9
print('The middle array is \n',z,'\n')

output[1:4,1:4] = z
print('Final result is \n',output)

initial input is 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

The middle array is 
 [[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]] 

Final result is 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays !!

In [200]:
a = np.array([1,2,3])
b = a
b[0]= 100
print(b)
print(a)

#Here we only made changes in b but elements of array "a" also changed
# So we need to avoid simply copying an array


[100   2   3]
[100   2   3]


In [204]:
# You can use the following method to create a new array which 
# wont point the array in the same memory location as the initial one

a = np.array([1,2,3])
b = np.array(a)
#Or alternatively you can use "b = a.copy()"
print(b)

b[0] = 100
print(b)
print(a)

[1 2 3]
[100   2   3]
[1 2 3]


## ***Mathematics***

In [7]:
a = np.array([[1,3,5,7],[1,0,1,0]])
a

array([[1, 3, 5, 7],
       [1, 0, 1, 0]])

In [206]:
a+2

array([3, 5, 7, 9])

In [208]:
a*4

array([ 4, 12, 20, 28])

In [210]:
a//5

array([0, 0, 1, 1], dtype=int32)

In [212]:
a/5

array([0.2, 0.6, 1. , 1.4])

In [8]:
b = np.array([[1,0,1,0],[1,3,5,7]])
a+b

array([[2, 3, 6, 7],
       [2, 3, 6, 7]])

In [9]:
a*b

array([[1, 0, 5, 0],
       [1, 0, 5, 0]])

In [216]:
a**2

array([ 1,  9, 25, 49])

In [240]:
# Take the sin of all values of array
np.sin(a)

# Other Trignometric functions can also be applied in similar fashion on array

array([[0.84147098, 0.84147098],
       [0.84147098, 0.84147098]])

##### Similarly many other Maths routine methods are inbuilt present in numpy

You can refer to "https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqazV1TXI2TmZrUzhnRlcwdWpjTlFXeTFLcllDZ3xBQ3Jtc0trTkY5RDJVa3NkMjVBX2hTajVjT2cyelBfblBHUkxWN2cxSVRMY0ZrNWZmWXphQWZQMmNlRVpTVnFFcHJROW1UVmR3ZF85S2JrMnFzd2VWbEM3aUt3ZmxFVHVPcXRsclZSWHpZVUtaTnlETEFNV1cwSQ&q=https%3A%2F%2Fdocs.scipy.org%2Fdoc%2Fnumpy%2Freference%2Froutines.math.html&v=GB9ByFAIAH4"

### Linear Algebra

In [276]:
#Matrix multiplication using matmul() function

a = np.ones((2,2),dtype = 'int32')
print(a)

b = np.full((2,2),2)
print(b)

np.matmul(a,b)

[[1 1]
 [1 1]]
[[2 2]
 [2 2]]


array([[4, 4],
       [4, 4]])

In [239]:
# To calculate determinant of matrix we use 
# linalg methods in numpy
c = np.identity(3)
np.linalg.det(c)
np.linalg.det(a)


0.0

#### Similarly many other linear algebra functions are inbuilt present in numpy :
1. Determinants
2. Trace
3. Singular Vector Decomposition
4. Eigenvalues
5. Matrix Norm
6. Inverse
7. Etc....

 Refer to (https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbkwyMU93NnJNNURIcjdPU1pXS2dtaGlHQmtiUXxBQ3Jtc0tuUS1XMGNURThvcTdMQ2dWNkQ2ZUZqLXJvYnBxRDE4S2RzZTlmcDhoMHpmSjFub3pYX1R1RlRobTJOemZiZGE4OGJLdmZTYl9CTzdPSFhvdU9fOF95VE5QQnBLNG9FLTNRMzNwblNnZkx6NFd4OHpGRQ&q=https%3A%2F%2Fdocs.scipy.org%2Fdoc%2Fnumpy%2Freference%2Froutines.linalg.html&v=GB9ByFAIAH4)

### Statistics

In [270]:
stats = np.array([[1,22,3],[43,5,6]])
stats

array([[ 1, 22,  3],
       [43,  5,  6]])

In [272]:
y = np.min(stats)
print(y) # minimum in complete array/matrix
np.min(stats,axis = 1) #axis = 1 means min in all rows

1


array([1, 5])

In [273]:
y = np.max(stats)
print(y) # Maximum in complete array/matrix
np.max(stats,axis =0) #axis = 0 means max in all columns

43


array([43, 22,  6])

In [275]:
w = np.sum(stats) # Sum of all the elements in array
x = np.sum(stats,axis = 1)#Axis = 1 means sum of elements row wise
y = np.sum(stats,axis = 0) #Axis = 0 means sum of elements column wise
print(w)
print(x)
print(y)

80
[26 54]
[44 27  9]


### Reorganizing Arrays

In [14]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

after = before.reshape((2,2,2))
# after = np.reshape(before,(2,2,2))
after

# You need to ensure while reshaping the array, 
# the size of the array remains 
# consistent before and after reshaping of the array
# For example previously the size was 2*4 = 8 
# and now the size is 2*2*2 = 8 which is consistent

(2, 4)


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [294]:
# Vertical stacking of vectors
v1 = np.array([1,2,4,5])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])

array([[1, 2, 4, 5],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 4, 5]])

In [307]:
# Horizontal stacking vectors
np.hstack([v1,v2,v1,np.full_like(v1,1)])

array([1, 2, 4, 5, 5, 6, 7, 8, 1, 2, 4, 5, 1, 1, 1, 1])

### Miscellaneous

##### Load Data from file

In [310]:
filedata = np.genfromtxt('filedata.txt',delimiter = ",")
filedata = filedata.astype('int32')
filedata

array([[    9,    99,   999,  9999, 99999],
       [    1,     2,     3,     4,     5],
       [   10,   100,    11,   101,  1000]])

#### Boolean Masking and Advanced indexing

In [325]:

print(filedata >= 90)
# Will check for each item in array and return True or False
# based on given condition against each element

# We can use the above conditions as index as well
# and wherever the condition is true, it will return the 
# corresponding values from the original array where condition
# hold True
# For Example -->

filedata[filedata<=90]#returns all values from original array

[[False  True  True  True  True]
 [False False False False False]
 [False  True False  True  True]]


array([ 9,  1,  2,  3,  4,  5, 10, 11])

In [328]:
# You can also check for a particular columns or row
np.any(filedata>50, axis = 1) # Axis = 0 for cols and axis = 1 for rows

array([ True, False,  True])

In [329]:
# Can apply more than one condition using &(and) and |(or) 
((filedata > 50) & (filedata <500))

array([[False,  True, False, False, False],
       [False, False, False, False, False],
       [False,  True, False,  True, False]])

#### You can index with a list in Numpy

In [338]:
a = np.array([[1,2,3,4,5,6,7,8,9],[11,12,13,14,15,16,17,18,19],[21,22,23,24,25,26,27,28,29]])
a[:,[1,2,8]] # the requisite cols are passed as a list

array([[ 2,  3,  9],
       [12, 13, 19],
       [22, 23, 29]])

In [341]:
a[[0,1,2],[1,2,3]] #Advanced indexing
# first pass on the list of rows required and then pass
# on the list of corresponding column required

a[[0,2],4:]

array([[ 5,  6,  7,  8,  9],
       [25, 26, 27, 28, 29]])